#cloud-config
package_upgrade: true

packages:
  - docker

runcmd:
  - until [ -e /dev/xvdb ]; do sleep 5; done
  - mkfs.xfs /dev/xvdb
  - echo '/dev/xvdb /data xfs defaults 0 0' >>  /etc/fstab
  - mkdir /data
  - mount /data
  - service docker restart
  - start ecs

write_files:
  - owner: root:root
    path: /etc/ecs/ecs.config
    content: ECS_CLUSTER=${ecs_cluster}

  - owner: root:root
    path: /opt/scripts/gitlab-backup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      docker ps --filter "label=service=gitlab-server" --quiet | while read line; do
        docker exec $line gitlab-rake gitlab:backup:create CRON=1
      done

  - owner: root:root
    path: /etc/cron.d/gitlab
    content: |
      10 5 * * * root /opt/scripts/gitlab-backup.sh
