#cloud-config
package_upgrade: true

yum_repos:
  runner_gitlab-runner:
    name: runner_gitlab-runner
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/6/$basearch
    repo_gpgcheck: 1
    gpgcheck: 0
    enabled: 1
    gpgkey: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

packages:
  - gitlab-runner
  - docker

write_files:
  - owner: root:root
    path: /etc/gitlab-runner/ca.pem
    content: ${GITLAB_SELF_SIGNED_CA}
  - owner: root:root
    path: /etc/gitlab-runner/config.toml
    content: |
      concurrent = ${GITLAB_CONCURRENT_JOB}
      check_interval = ${GITLAB_CHECK_INTERVAL}

runcmd:
  - export REGISTER_NON_INTERACTIVE="true"
  - export REGISTER_LOCKED="false"
  - export REGISTER_RUN_UNTAGGED="true"
  - export CI_SERVER_URL="${GITLAB_RUNNER_URL}"
  - export CI_SERVER_TLS_CA_FILE="/etc/gitlab-runner/ca.pem"
  - export REGISTRATION_TOKEN="${GITLAB_RUNNER_TOKEN}"
  - export RUNNER_EXECUTOR="docker"
  - export DOCKER_IMAGE="${GITLAB_IMAGE}"
  - export CACHE_TYPE="s3"
  - export S3_BUCKET_NAME="${GITLAB_CACHE_BUCKET_NAME}"
  - export S3_BUCKET_LOCATION="${REGION}"
  - export S3_CACHE_INSECURE="false"
  - export CACHE_SHARED="true"
  - chkconfig docker on ; service docker start
  - chkconfig gitlab-runner on; service gitlab-runner start
  - until gitlab-runner register; do sleep 5; done
